#!/bin/sh

cd $(dirname $0)
cd ../

echo "mbed-tools compile --toolchain \$MBED_TOOLCHAIN --mbed-target \$MBED_TARGET" | cat .env - | sh
sudo cp ./cmake_build/kotodori-gateway-mbed.bin $(echo "echo \$DEPLOY_DIR" | cat .env - | sh)
